# Generated by Django 3.2.19 on 2023-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0167_alter_problem_submission_source_visibility_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='submission_source_visibility_mode',
            field=models.CharField(choices=[('F', 'Follow global setting'), ('A', 'Always visible'), ('S', 'Visible if problem solved'), ('O', 'Only own submissions')], default='O', max_length=1, verbose_name='submission source visibility'),
        ),
    ]
