# Generated by Django 3.2.25 on 2024-06-22 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0168_add_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='message title')),
                ('content', models.TextField(verbose_name='message body')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='message timestamp')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='judge.profile', verbose_name='sender')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='judge.profile', verbose_name='target')),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='push_announcements',
            field=models.BooleanField(default=True, help_text='Notify users when there are new announcements.', verbose_name='push announcements'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text="Doesn't have magic ability to auto-publish due to backward compatibility", null=True, verbose_name='date of publishing'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='publicly visible'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcase_visibility_mode',
            field=models.CharField(choices=[('O', 'Visible for authors'), ('C', 'Visible if user is not in a contest'), ('A', 'Always visible')], default='O', max_length=1, verbose_name='Testcase visibility'),
        ),
        migrations.CreateModel(
            name='PrivateMessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='judge.PrivateMessage', verbose_name='messages in the thread')),
            ],
        ),
    ]
