# Generated by Django 3.2.19 on 2023-06-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0167_profile_upload_image_perm'),
        ('judge', '0168_alter_problem_submission_source_visibility_mode'),
    ]

    operations = [
    ]
