# Generated by Django 3.2.25 on 2024-06-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0169_auto_20240622_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='posted time')),
                ('category', models.CharField(max_length=1000, verbose_name='category')),
                ('html_link', models.TextField(default='', max_length=1000, verbose_name='html link to comments, used for non-comments')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='who trigger, used for non-comment')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.comment', verbose_name='comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='judge.profile', verbose_name='owner')),
            ],
        ),
    ]
