# Generated by Django 3.2.25 on 2024-07-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0170_notification_notificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_class',
            field=models.CharField(default='rank-others', max_length=20),
        ),
    ]
