# Generated by Django 3.2.25 on 2024-06-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0169_auto_20240622_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg_time', models.DateTimeField(db_index=True, null=True, verbose_name='last seen')),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to='judge.profile', verbose_name='user 1')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to='judge.profile', verbose_name='user 2')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='posted time')),
                ('body', models.TextField(max_length=8192, verbose_name='body of comment')),
                ('hidden', models.BooleanField(default=False, verbose_name='is hidden')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_box.room', verbose_name='room id')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Ignore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_users', models.ManyToManyField(to='judge.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_chat_users', to='judge.profile', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='last seen')),
                ('unread_count', models.IntegerField(db_index=True, default=0)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_box.room', verbose_name='room id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['hidden', 'room', '-id'], name='chat_box_me_hidden_b2307a_idx'),
        ),
    ]
